spring:
  application:
    name: reservapro-backend

  datasource:
    driver-class-name: org.postgresql.Driver
    password: sa
    username: root
    jdbc-url: jdbc:postgresql://reservapro_database:5432/testedb

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082